### PR TITLE
Fix usage with Composer <2.3

### LINKED ISSUE #124: Plugin fails to work with Composer < 2.3
This plugin can no longer be used with Composer 2.2 even though the `composer.json` says it's compatible, due to https://github.com/bamarni/composer-bin-plugin/pull/86

```
PHP Fatal error:  Uncaught Error: Call to undefined method Bamarni\Composer\Bin\BinCommand::requireComposer() in /tmp/tmp.Kzy6XI6bnx/vendor/bamarni/composer-bin-plugin/src/BinCommand.php:91
Stack trace:
#0 phar:///usr/local/lib/composer-2.2.14/vendor/symfony/console/Command/Command.php(245): Bamarni\Composer\Bin\BinCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 phar:///usr/local/lib/composer-2.2.14/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/lib/composer-2.2.14/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Bamarni\Composer\Bin\BinCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/lib/composer-2.2.14/src/Composer/Console/Application.p in /tmp/tmp.Kzy6XI6bnx/vendor/bamarni/composer-bin-plugin/src/BinCommand.php on line 91
```

### PR DESCRIPTION
**Pull request by theofidry**
Closes #124

### CODE REVIEW

File: src/Command/BinCommand.php [hunk 1]
```diff
@@ -94,7 +94,8 @@ public function isProxyCommand(): bool
 
     public function execute(InputInterface $input, OutputInterface $output): int
     {
-        $config = Config::fromComposer($this->requireComposer());
+        // Switch to requireComposer() once Composer 2.3 is set as the minimum
+        $config = Config::fromComposer($this->getComposer());
```
Comment (AndreasA) [inline src/Command/BinCommand.php:98]: @theofidry maybe add a check if `requireComposer` exist and if so, use it?

that way it would continue working in potential newer composer version which might not have `getComposer` anymore. 

Though as it is a breaking change it probably won't happen prior to composer 3.x and until then there will most likely be a plugin version for 2.3 or higher,, so it is probably unnecessary.

Comment (theofidry) [reply src/Command/BinCommand.php:98]: Done in #135
